### ISSUE TITLE
Possibility to update hex (rebar3_sbom)

### ISSUE THREAD

**Issue by fnchooft** [voltone/rebar3_sbom#3]
Great plugin, seems that hex is not providing the latest version from master branch.

{rebar3_sbom, "0.5.0"} - is pointing to a tag 0.5.0 - but I could not locate it in this github-repo.

Since the master fixes an issue which I hit - maybe one could redeploy it on hex with a new version.

Thanks again,
Kind regards.

**Comment by voltone** [comment]
Ok, done. Thanks for the heads-up!
