### ISSUE TITLE
bom.xml does not contain a complete list of dependencies

### ISSUE THREAD

**Issue by happydroid** [voltone/rebar3_sbom#4]
Hi there and thanks for this plugin.

**Problem**
I don't have much experience with erlang/rebar3 but I need to use this plugin. For some projects, a complete list of dependencies is not generated, although in my opinion they should be in the bom.xml file. For example:

**Project one**
https://github.com/erlcloud/erlcloud

part of file rebar.config:
```
{deps, [
        {jsx, "2.11.0"},
        {lhttpc, "1.6.2"},
        {eini, "1.2.9"},
        {base16, "1.0.0"}
       ]}.

{overrides,
 [
  %% do not pull in the covertool plugin or repo, cause it fetches rebar and
  %% breaks rebar3!
  {override, eini, [{plugins, []},{deps, []}]}
 ]}.

{profiles, [
            {test, [{deps, [{meck, "0.9.0"}]}, {erl_opts, [warnings_as_errors]}]}
           ,{warnings, [{erl_opts, [warnings_as_errors]}]}
           ]}.
```
As I understand it, the dependencies of this project will be jsx, lhttpc, eini, base16
Output of command `rebar3 deps`:
```
===> Verifying dependencies...
base16 (locked pkg source)
eini (locked pkg source)
jsx (locked pkg source)
lhttpc (locked pkg source)
```
Bom.xml does not contain any components for this project with any profiles (default, default, test, docs)
I mean this: `rebar3 as default,test,docs sbom -o dev_bom.xml`

**Project two**
https://github.com/kivra/restclient

part of file rebar.config:
```
{deps, [{hackney,"1.17.4"},
        {jsx,"2.11.0"},
        {erlsom,"1.5.0"}
       ]}.

{profiles,
    [{test, [
        {erl_opts, [nowarn_export_all]},
        {deps, [ proper
               , {meck, "0.8.13"}
               ]}
    ]}
]}.
```
As I understand it, the dependencies of this project will be hackney, jsx, erlsom
Output of command `rebar3 deps`:
```
===> Verifying dependencies...
erlsom (locked pkg source)
hackney (locked pkg source)
jsx* (locked package 2.9.0 <> pkg source)
```
Bom.xml does not contain any components for this project with any profiles (default, default, test, docs)
I mean this: `rebar3 as default,test,docs sbom -o dev_bom.xml`

**Question**
I randomly chose projects for testing, I think I can find such patterns for other projects. Tell me please, does the plugin work correctly or should these dependencies be contained in the bom.xml report?

**Comment by voltone** [comment]
Which version of rebar3 are you using?

**Comment by voltone** [comment]
Thanks for the report, I was able to reproduce  and fix it.

Can you please try again with master branch, e.g.:

```erlang
    {plugins, [
        {rebar3_sbom, {git, "https://github.com/voltone/rebar3_sbom"}}
    ]}.
```

I need to fix #6 before I can release a new version to Hex.

**Comment by happydroid** [comment]
Hi @voltone , new version of plugin works well, a problem solved, thanks a lot :)

**Comment by voltone** [comment]
Now also on hex.pm: https://hex.pm/packages/rebar3_sbom/0.6.0
